/**
 * Harper Database - Roman Egypt Economic Data
 * 
 * Source: Kyle Harper, DARMC Scholarly Data Series 2016-5
 * Citation: Harper, K. 2016. Database of Prices, Wages, and Rents for Roman Egypt, 1-700 CE
 * Original: "People, Plagues, and Prices in the Roman World" JEH 76 (2016), 803-39
 */

const HARPER_DATA = {
  metadata: {
    source: "Kyle Harper, DARMC Scholarly Data Series 2016-5",
    citation: "Harper, K. 2016. Database of Prices, Wages, and Rents for Roman Egypt, 1-700 CE",
    original_article: "People, Plagues, and Prices in the Roman World: JEH 76 (2016), 803-39",
    app_name: "罗马斩杀线",
    app_name_en: "Roman Kill Line"
  },

  time_periods: [
    {
      id: "julio_claudian",
      name_en: "Julio-Claudian Dynasty",
      name_zh: "儒略-克劳狄王朝",
      name_alt: "早期罗马帝国",
      start_year: 27,
      end_year: 68,
      currency_system: "silver_denarius",
      primary_coins: ["aureus", "denarius", "sestertius", "as"],
      description_en: "The golden age of the early Empire. Stable currency, prosperous Egypt.",
      description_zh: "帝国初期的黄金时代。货币稳定，埃及繁荣。这是《出埃及记》之后、耶稣时代的罗马。",
      historical_events: ["Augustus reforms", "Tiberius", "Caligula", "Claudius conquest of Britain", "Nero's Great Fire"],
      avg_wheat_price_dr_art: 7.0,
      avg_daily_wage_obols: 5.0,
      silver_content_denarius_g: 3.9,
      gold_content_aureus_g: 7.87,
      denarii_per_aureus: 25,
      icon: "julio-claudian"
    },
    {
      id: "flavian_antonine",
      name_en: "Flavian-Antonine Era",
      name_zh: "弗拉维-安敦尼时代",
      name_alt: "罗马盛世",
      start_year: 69,
      end_year: 192,
      currency_system: "silver_denarius",
      primary_coins: ["aureus", "denarius", "sestertius", "as"],
      description_en: "The Five Good Emperors. Peak of Roman prosperity and stability.",
      description_zh: "五贤帝时代。罗马繁荣与稳定的巅峰。图拉真征服达契亚，哈德良建长城，马可·奥勒留写《沉思录》。",
      historical_events: ["Colosseum built", "Trajan conquests", "Hadrian's Wall", "Marcus Aurelius", "Antonine Plague 165-180"],
      avg_wheat_price_dr_art: 8.0,
      avg_daily_wage_obols: 7.0,
      silver_content_denarius_g: 3.4,
      gold_content_aureus_g: 7.3,
      denarii_per_aureus: 25,
      icon: "flavian-antonine"
    },
    {
      id: "severan",
      name_en: "Severan Dynasty",
      name_zh: "塞维鲁王朝",
      name_alt: "军人皇帝前期",
      start_year: 193,
      end_year: 235,
      currency_system: "silver_denarius_debased",
      primary_coins: ["aureus", "denarius", "sestertius"],
      description_en: "Military emperors. Currency debasement begins in earnest.",
      description_zh: "军人皇帝时代。货币贬值开始加速。卡拉卡拉大浴场建成，罗马公民权扩展到全帝国。",
      historical_events: ["Septimius Severus", "Caracalla's Edict 212", "Baths of Caracalla"],
      avg_wheat_price_dr_art: 16.0,
      avg_daily_wage_obols: 14.0,
      silver_content_denarius_g: 2.5,
      gold_content_aureus_g: 6.5,
      denarii_per_aureus: 25,
      icon: "severan"
    },
    {
      id: "crisis_3c",
      name_en: "Crisis of the Third Century",
      name_zh: "三世纪危机",
      name_alt: "军营皇帝时代",
      start_year: 235,
      end_year: 284,
      currency_system: "antoninianus",
      primary_coins: ["aureus", "antoninianus", "denarius"],
      description_en: "50 years of chaos. Rapid inflation, barbarian invasions, plague.",
      description_zh: "五十年混乱。恶性通胀、蛮族入侵、瘟疫肆虐。皇帝如走马灯更换。银币几乎变成铜币。",
      historical_events: ["26 emperors in 50 years", "Plague of Cyprian", "Gallic Empire", "Palmyrene Empire"],
      avg_wheat_price_dr_art: 20.0,
      avg_daily_wage_obols: 28.0,
      silver_content_denarius_g: 1.5,
      gold_content_aureus_g: 5.5,
      denarii_per_aureus: 25,
      icon: "crisis"
    },
    {
      id: "late_roman",
      name_en: "Late Roman Empire",
      name_zh: "晚期罗马帝国",
      name_alt: "拜占庭前期",
      start_year: 364,
      end_year: 476,
      currency_system: "solidus_gold",
      primary_coins: ["solidus", "tremissis", "siliqua", "nummus"],
      description_en: "Gold solidus standard. Western Empire falls. Eastern Empire continues.",
      description_zh: "金索里杜斯本位。西罗马帝国灭亡（476年），东罗马继续存在。日耳曼蛮族建立王国。",
      historical_events: ["Valentinian I", "Theodosius I", "Visigoths sack Rome 410", "Vandals sack Rome 455", "Romulus Augustulus deposed 476"],
      avg_wheat_art_per_sol: 10.0,
      gold_content_solidus_g: 4.5,
      icon: "late-roman"
    },
    {
      id: "byzantine_early",
      name_en: "Early Byzantine",
      name_zh: "拜占庭早期",
      name_alt: "查士丁尼时代",
      start_year: 476,
      end_year: 641,
      currency_system: "solidus_gold",
      primary_coins: ["solidus", "tremissis", "follis", "nummus"],
      description_en: "Justinian's reconquests. Hagia Sophia. Last era of Harper's Egyptian data.",
      description_zh: "查士丁尼大帝的光复战争。圣索菲亚大教堂建成。。",
      historical_events: ["Justinian I", "Nika Riots 532", "Hagia Sophia 537", "Plague of Justinian 541", "Arab conquest of Egypt 641"],
      avg_wheat_art_per_sol: 12.0,
      gold_content_solidus_g: 4.5,
      icon: "byzantine"
    }
  ],

  currency_data: {
    modern_to_metal: {
      gold_usd_per_gram: 65.0,
      silver_usd_per_gram: 0.8,
      bronze_usd_per_gram: 0.008,
      cny_per_usd: 7.2,
      eur_per_usd: 0.92
    },
    roman_coins: {
      aureus_early: { gold_g: 7.87, value_denarii: 25 },
      aureus_late: { gold_g: 6.5, value_denarii: 25 },
      denarius_augustan: { silver_g: 3.9, value_sestertii: 4 },
      denarius_neronian: { silver_g: 3.4, value_sestertii: 4 },
      denarius_severan: { silver_g: 2.5, value_sestertii: 4 },
      denarius_crisis: { silver_g: 1.5, value_sestertii: 4 },
      sestertius: { brass_g: 25.0, value_asses: 4 },
      dupondius: { brass_g: 12.5, value_asses: 2 },
      as: { copper_g: 10.0, value_base: 1 },
      solidus: { gold_g: 4.5, value_base: 1, standard: "72_per_pound" },
      tremissis: { gold_g: 1.5, value_solidi: 0.333 },
      siliqua: { silver_g: 2.0, value_per_solidus: 24 },
      follis_early: { bronze_g: 10.0, silver_wash: true },
      nummus: { bronze_g: 3.0 }
    }
  },

  wheat_prices: {
    "1_3c": [
      { year: 45, year_min: 45, year_max: 45, price_dr_art: 6.83, silver_g_hl: 16.95, nome: "Arsinoites", source: "P. Mich. 2.127", period: "julio_claudian" },
      { year: 46, year_min: 46, year_max: 46, price_dr_art: 8.73, silver_g_hl: 21.7, nome: "Arsinoites", source: "P. Mich. 2.123", period: "julio_claudian" },
      { year: 46.5, year_min: 46, year_max: 47, price_dr_art: 6.0, silver_g_hl: 14.9, nome: "Arsinoites", source: "SB 20.14576.34", period: "julio_claudian" },
      { year: 78.5, year_min: 78, year_max: 79, price_dr_art: 10.67, silver_g_hl: 23.1, nome: "Hermopolites", source: "SB 8.9699", period: "flavian_antonine" },
      { year: 100, year_min: 75, year_max: 125, price_dr_art: 5.0, silver_g_hl: 10.8, nome: "Arsinoites", source: "P. Louvre 2.103", period: "flavian_antonine" },
      { year: 124, year_min: 124, year_max: 124, price_dr_art: 9.0, silver_g_hl: 19.5, nome: "Hermopolites", source: "P. Sarap. 60.10", period: "flavian_antonine" },
      { year: 115, year_min: 100, year_max: 130, price_dr_art: 7.0, silver_g_hl: 15.2, nome: "Hermopolites", source: "P. Sarap. 92.18-19", period: "flavian_antonine" },
      { year: 128, year_min: 128, year_max: 128, price_dr_art: 12.0, silver_g_hl: 26.0, nome: "Hermopolites", source: "P. Sarap. 79b", period: "flavian_antonine" },
      { year: 138.5, year_min: 138, year_max: 139, price_dr_art: 5.6, silver_g_hl: 12.1, nome: "Oxyrhynchites", source: "PSI 4.281", period: "flavian_antonine" },
      { year: 160, year_min: 160, year_max: 160, price_dr_art: 10.0, silver_g_hl: 21.7, nome: "Arsinoites", source: "P. Berl. Leigh. 2.39", period: "flavian_antonine" },
      { year: 192, year_min: 192, year_max: 192, price_dr_art: 18.67, silver_g_hl: 40.43, nome: "Arsinoites", source: "P. Cair. Goodsp. 30", period: "flavian_antonine" },
      { year: 187.5, year_min: 175, year_max: 200, price_dr_art: 12.0, silver_g_hl: 26.0, nome: "Arsinoites", source: "SB 16.12607", period: "flavian_antonine" },
      { year: 187.5, year_min: 175, year_max: 200, price_dr_art: 18.0, silver_g_hl: 39.0, nome: "Arsinoites", source: "P. Iand. 6.94", period: "flavian_antonine" },
      { year: 216.5, year_min: 202, year_max: 231, price_dr_art: 20.0, silver_g_hl: 43.3, nome: "Arsinoites", source: "P. Lund 4.11", period: "severan" },
      { year: 216.5, year_min: 202, year_max: 232, price_dr_art: 16.0, silver_g_hl: 34.7, nome: "Oxyrhynchites", source: "P. NYU 2.8", period: "severan" },
      { year: 216, year_min: 215, year_max: 217, price_dr_art: 16.4, silver_g_hl: 35.5, nome: "Arsinoites", source: "P. Louvre 1.51", period: "severan" },
      { year: 217.5, year_min: 217, year_max: 218, price_dr_art: 14.57, silver_g_hl: 31.59, nome: "Arsinoites", source: "P. Louvre 1.54", period: "severan" },
      { year: 234, year_min: 226, year_max: 242, price_dr_art: 12.0, silver_g_hl: 26.0, nome: "Arsinoites", source: "P. Laur. 1.11", period: "severan" },
      { year: 249, year_min: 249, year_max: 249, price_dr_art: 24.0, silver_g_hl: 52.0, nome: "Arsinoites", source: "P. Flor. 1.9b", period: "crisis_3c" },
      { year: 250, year_min: 250, year_max: 250, price_dr_art: 20.0, silver_g_hl: 43.3, nome: "Arsinoites", source: "P. Prag. Varcl. 2.2", period: "crisis_3c" },
      { year: 251, year_min: 251, year_max: 251, price_dr_art: 20.0, silver_g_hl: 43.3, nome: "Arsinoites", source: "SB 20.14645", period: "crisis_3c" },
      { year: 252, year_min: 252, year_max: 252, price_dr_art: 24.0, silver_g_hl: 52.0, nome: "Arsinoites", source: "P. Prag. Varcl. 2.4", period: "crisis_3c" },
      { year: 253, year_min: 253, year_max: 253, price_dr_art: 16.0, silver_g_hl: 34.7, nome: "Arsinoites", source: "SB 20.14197", period: "crisis_3c" },
      { year: 255, year_min: 255, year_max: 255, price_dr_art: 16.0, silver_g_hl: 34.7, nome: "Arsinoites", source: "BGU 1.14", period: "crisis_3c" },
      { year: 259, year_min: 259, year_max: 259, price_dr_art: 16.0, silver_g_hl: 34.7, nome: "Arsinoites", source: "P. Prag. 3.236", period: "crisis_3c" },
      { year: 260, year_min: 260, year_max: 260, price_dr_art: 16.0, silver_g_hl: 34.7, nome: "Oxyrhynchites", source: "P. Oxy. 49.3513", period: "crisis_3c" },
      { year: 263, year_min: 263, year_max: 263, price_dr_art: 12.0, silver_g_hl: 26.0, nome: "Arsinoites", source: "P. Prag. 3.238", period: "crisis_3c" },
      { year: 270, year_min: 270, year_max: 270, price_dr_art: 24.0, silver_g_hl: 52.0, nome: "Oxyrhynchites", source: "P. Erl. 101", period: "crisis_3c" },
      { year: 282.5, year_min: 275, year_max: 290, price_dr_art: 240.0, silver_g_hl: 26.0, nome: "Oxyrhynchites", source: "P. Oxy. 75.5063", period: "crisis_3c" }
    ],
    "4c": [
      { year: 301, price_den_art: 640, silver_g_hl: 22.35, nome: "Hermopolites", source: "CPR 6.75", period: "tetrarchy_constantine" },
      { year: 304.5, price_den_art: 1200, silver_g_hl: 31.2, nome: "Oxyrhynchites", source: "P. Oxy. 36.2798", period: "tetrarchy_constantine" },
      { year: 305, price_den_art: 852, silver_g_hl: 21.41, nome: "Hermopolites", source: "SB 20.14657", period: "tetrarchy_constantine" },
      { year: 311, price_den_art: 1200, silver_g_hl: 26.0, nome: "Arsinoites", source: "P. Cair. Isid. 11", period: "tetrarchy_constantine" },
      { year: 312.5, price_den_art: 2000, silver_g_hl: 17.18, nome: "Arsinoites", source: "P. NYU 1.18", period: "tetrarchy_constantine" },
      { year: 314, price_den_art: 7000, silver_g_hl: 40.73, nome: "Hermopolites", source: "CPR 8.22", period: "tetrarchy_constantine" },
      { year: 315, price_den_art: 3000, silver_g_hl: 17.45, nome: "Arsinoites", source: "SB 5.7621", period: "tetrarchy_constantine" },
      { year: 327, price_den_art: 17333, silver_g_hl: 11.17, nome: "Oxyrhynchites", source: "PSI 4.309", period: "tetrarchy_constantine" },
      { year: 335, price_den_art: 84000, silver_g_hl: 20.6, nome: "Alexandria", source: "P. Lond. 6.1914", period: "tetrarchy_constantine" },
      { year: 338, price_den_art: 144000, silver_g_hl: 27.92, nome: "Oxyrhynchites", source: "SB 16.12648", period: "tetrarchy_constantine" },
      { year: 340, price_den_art: 275000, silver_g_hl: 34.1, nome: "Oxyrhynchites", source: "P. Oxy. 54.3773", period: "tetrarchy_constantine" },
      { year: 345, price_den_art: 300000, silver_g_hl: 27.34, nome: "Arsinoites", source: "P. Abinn. 68", period: "tetrarchy_constantine" },
      { year: 352.5, price_den_art: 2004000, silver_g_hl: 9.58, nome: "Middle Egypt", source: "P. Princ. 3.183", period: "tetrarchy_constantine" },
      { year: 357.5, price_den_art: 5076000, silver_g_hl: 13.12, nome: "Middle Egypt", source: "P. Stras. 6.595", period: "tetrarchy_constantine" },
      { year: 359, price_den_art: 8202000, silver_g_hl: 25.1, nome: "Oxyrhynchites", source: "P. Oxy. 51.3625", period: "tetrarchy_constantine" }
    ],
    "5_7c": [
      { year: 370, art_per_sol: 8.75, silver_g_hl: 19.45, carats_hl: 3.18, nome: "Dakhla Oasis", source: "P. Kellis 4.96", period: "late_roman" },
      { year: 375, art_per_sol: 11.2, silver_g_hl: 14.91, carats_hl: 5.52, nome: "Oxyrhynchites", source: "P.Col. 8.238", period: "late_roman" },
      { year: 423, art_per_sol: 11.5, silver_g_hl: 14.52, carats_hl: 5.38, nome: "various", source: "P. Oxy. 51.3628-3636", period: "late_roman" },
      { year: 445, art_per_sol: 8.62, silver_g_hl: 19.37, carats_hl: 7.17, nome: "Numidia/Mauretania", source: "Nov. Val. III 13.4", period: "late_roman" },
      { year: 450, art_per_sol: 10.0, silver_g_hl: 16.7, carats_hl: 6.18, nome: "Hermopolites", source: "Kl. Form. 769", period: "late_roman" },
      { year: 500, art_per_sol: 14.0, silver_g_hl: 11.93, carats_hl: 4.42, nome: "Hermopolites", source: "PSI 46", period: "byzantine_early" },
      { year: 504, art_per_sol: 4.5, silver_g_hl: 37.11, carats_hl: 13.74, nome: "Oxyrhynchites", source: "P. Oxy. 62.4349", period: "byzantine_early" },
      { year: 512.5, art_per_sol: 12.0, silver_g_hl: 13.91, carats_hl: 5.15, nome: "Hermopolites", source: "P. Baden 4.95", period: "byzantine_early" },
      { year: 538, art_per_sol: 8.0, silver_g_hl: 20.87, carats_hl: 7.73, nome: "Aphrodites", source: "P.Cair. Masp. 1.67062", period: "byzantine_early" },
      { year: 540, art_per_sol: 10.37, silver_g_hl: 16.1, carats_hl: 5.96, nome: "Antaiopolites", source: "P.Cair. Masp. 2.67229", period: "byzantine_early" },
      { year: 541, art_per_sol: 8.62, silver_g_hl: 19.37, carats_hl: 7.17, nome: "Antinoopolites", source: "P.Cair. Masp. 3.67320", period: "byzantine_early" },
      { year: 545, art_per_sol: 5.02, silver_g_hl: 33.26, carats_hl: 12.32, nome: "Aphrodites", source: "P.Cair. Masp. 2.67138", period: "byzantine_early" },
      { year: 550, art_per_sol: 10.0, silver_g_hl: 16.7, carats_hl: 6.18, nome: "Lycopolites", source: "P.Cair. Masp. 3.67289", period: "byzantine_early" },
      { year: 557, art_per_sol: 20.0, silver_g_hl: 8.35, carats_hl: 3.09, nome: "Oxyrhynchites", source: "P. Oxy. 16.1911", period: "byzantine_early" },
      { year: 566, art_per_sol: 14.0, silver_g_hl: 11.93, carats_hl: 4.42, nome: "Oxyrhynchites", source: "P. Oxy. 55.3805", period: "byzantine_early" },
      { year: 575, art_per_sol: 10.0, silver_g_hl: 16.7, carats_hl: 6.18, nome: "Oxyrhynchites", source: "P. Oxy. 16.1920", period: "byzantine_early" },
      { year: 587.5, art_per_sol: 10.0, silver_g_hl: 16.7, carats_hl: 6.18, nome: "Oxyrhynchites", source: "P. Oxy. 16.2024", period: "byzantine_early" },
      { year: 592, art_per_sol: 10.0, silver_g_hl: 16.7, carats_hl: 6.18, nome: "Oxyrhynchites", source: "P. Oxy. 16.1909", period: "byzantine_early" },
      { year: 609, art_per_sol: 28.8, silver_g_hl: 5.8, carats_hl: 2.15, nome: "Memphites", source: "CPR 10.1", period: "byzantine_early" },
      { year: 650, art_per_sol: 13.5, silver_g_hl: 12.37, carats_hl: 4.58, nome: "Hermopolites", source: "P. Lond. 5.1907", period: "byzantine_early" },
      { year: 650, art_per_sol: 15.0, silver_g_hl: 11.13, carats_hl: 4.12, nome: "Arsinoites", source: "CPR 4.86", period: "byzantine_early" }
    ]
  },

  wages: {
    daily: [
      { year: 78, wage_type: "daily", occupation: "unskilled farm labor", amount: 3.42, unit: "obols", nome: "Hermopolites", source: "SB 8.9699", period: "flavian_antonine" },
      { year: 100, wage_type: "daily", occupation: "irrigation", amount: 7, unit: "obols", nome: "Oxyrhynchites", source: "P. Oxy. 6.971", period: "flavian_antonine" },
      { year: 104, wage_type: "daily", occupation: "workers", amount: 6, unit: "obols", nome: "Hermopolites", source: "P. Sarap. 70", period: "flavian_antonine" },
      { year: 105, wage_type: "daily", occupation: "harvest", amount: 6, unit: "obols", nome: "Euhemeria", source: "P. Fay. 102", period: "flavian_antonine" },
      { year: 109.5, wage_type: "daily", occupation: "unskilled farm labor", amount: 3.8, unit: "obols", nome: "Tebtynis", source: "P. Mil. Vogl. 4.212", period: "flavian_antonine" },
      { year: 128, wage_type: "daily", occupation: "misc farm work", amount: 6, unit: "obols", nome: "Hermopolites", source: "P. Sarap. 69", period: "flavian_antonine" },
      { year: 150, wage_type: "daily", occupation: "farm work", amount: 7, unit: "obols", nome: "Arsinoites", source: "BGU 13.2354", period: "flavian_antonine" },
      { year: 155, wage_type: "daily", occupation: "unskilled farm labor", amount: 6.02, unit: "obols", nome: "Tebtynis", source: "P. Mil. Vogl. 4.214", period: "flavian_antonine" },
      { year: 168, wage_type: "daily", occupation: "unskilled farm labor", amount: 10.77, unit: "obols", nome: "Tebtynis", source: "P. Mil. Vogl. 3.153", period: "flavian_antonine" },
      { year: 175, wage_type: "daily", occupation: "misc farm work", amount: 18, unit: "obols", nome: "Oxyrhynchites", source: "P. Oxy. 7.1049", period: "flavian_antonine" },
      { year: 240, wage_type: "daily", occupation: "misc farm work", amount: 18.2, unit: "obols", nome: "Arsinoites", source: "P. Mich. 11.620", period: "crisis_3c" },
      { year: 255, wage_type: "daily", occupation: "unskilled farm labor", amount: 50, unit: "obols", nome: "Memphites", source: "BGU 1.14", period: "crisis_3c" },
      { year: 258.5, wage_type: "daily", occupation: "unskilled farm labor", amount: 14, unit: "obols", nome: "Theadelphia", source: "P. Lond. 3.1170 v", period: "crisis_3c" },
      { year: 301, wage_type: "daily", occupation: "transport", amount: 250, unit: "denarii", nome: "Oxyrhynchites", source: "P. Oxy. 38.2859", period: "tetrarchy_constantine" },
      { year: 314, wage_type: "daily", occupation: "workers", amount: 500, unit: "denarii", nome: "Hermopolites", source: "CPR VIII 22", period: "tetrarchy_constantine" },
      { year: 325, wage_type: "daily", occupation: "transport", amount: 2000, unit: "denarii", nome: "Oxyrhynchites", source: "P. Oxy. 14.1626", period: "tetrarchy_constantine" },
      { year: 375, wage_type: "daily", occupation: "construction", amount: 0.033, unit: "solidus", nome: "Asia Minor", source: "Greg. Nyssa. Epist. 25", period: "late_roman" }
    ],
    yearly: [
      { year: 432, occupation: "rug weaving", amount: 3, unit: "solidi", nome: "Oxyrhynchites", source: "P. Rein. 2.105", period: "late_roman" },
      { year: 500, occupation: "police officer", amount: 3, unit: "solidi", nome: "Oxyrhynchites", source: "P. Iand. 37", period: "byzantine_early" },
      { year: 519, occupation: "farm supervisor", amount: 2, unit: "solidi", nome: "Oxyrhynchites", source: "P. Oxy. 57.3914", period: "byzantine_early" },
      { year: 550, occupation: "cook", amount: 2.4, unit: "solidi", nome: "Arsinoites", source: "SPP 3.164", period: "byzantine_early" },
      { year: 550, occupation: "workman", amount: 3, unit: "solidi", nome: "unknown", source: "P. Erl. 74", period: "byzantine_early" },
      { year: 550, occupation: "bath service", amount: 1.2, unit: "solidi", nome: "Oxyrhynchites", source: "P. Oxy. 16.2006", period: "byzantine_early" },
      { year: 588, occupation: "goldsmith helper", amount: 3, unit: "solidi", nome: "Oxyrhynchites", source: "P. Oxy 58.3933", period: "byzantine_early" },
      { year: 593, occupation: "irrigation work", amount: 1, unit: "solidi", nome: "Herakleopolites", source: "SPP 3.86", period: "byzantine_early" },
      { year: 600, occupation: "chief helper", amount: 2, unit: "solidi", nome: "Arsinoites", source: "SPP 3.2", period: "byzantine_early" },
      { year: 612, occupation: "estate paramilitary", amount: 4, unit: "solidi", nome: "Oxyrhynchites", source: "P. Oxy. 16.2045", period: "byzantine_early" },
      { year: 650, occupation: "carpentry", amount: 1.44, unit: "solidi", nome: "unknown", source: "P. Coll. Youtie 2.95", period: "byzantine_early" }
    ]
  },

  rents: {
    cash: [
      { year: 14, rent_dr_ar: 12.5, nome: "Arsinoites", source: "P. Mich. 5.310", notes: "private vineyard", period: "julio_claudian" },
      { year: 42, rent_dr_ar: 20.0, nome: "Arsinoites", source: "P. Mich. 5.311", notes: "grain land", period: "julio_claudian" },
      { year: 45, rent_dr_ar: 40.0, nome: "Arsinoites", source: "P. Mich. 2.121", notes: "good land", period: "julio_claudian" },
      { year: 46, rent_dr_ar: 28.0, nome: "Arsinoites", source: "P. Mich. 2.123", period: "julio_claudian" },
      { year: 62, rent_dr_ar: 36.0, nome: "Arsinoites", source: "BGU 7.1648", period: "julio_claudian" },
      { year: 78, rent_dr_ar: 60.0, nome: "Hermopolites", source: "SB 8.9699", notes: "Didymos estate", period: "flavian_antonine" },
      { year: 84, rent_dr_ar: 32.0, nome: "Arsinoites", source: "P. Fay. 93", period: "flavian_antonine" },
      { year: 89, rent_dr_ar: 48.0, nome: "Arsinoites", source: "CPR 1.24", period: "flavian_antonine" },
      { year: 95, rent_dr_ar: 50.0, nome: "Oxyrhynchites", source: "P. Oxy. 50.3587", period: "flavian_antonine" },
      { year: 99, rent_dr_ar: 40.0, nome: "Arsinoites", source: "BGU 2.538", period: "flavian_antonine" },
      { year: 102, rent_dr_ar: 44.0, nome: "Arsinoites", source: "P. Tebt. 2.375", period: "flavian_antonine" },
      { year: 117, rent_dr_ar: 60.0, nome: "Hermopolites", source: "P. Sarap. 4", period: "flavian_antonine" },
      { year: 120, rent_dr_ar: 64.0, nome: "Arsinoites", source: "P. Mich. 11.603", period: "flavian_antonine" },
      { year: 134, rent_dr_ar: 48.0, nome: "Arsinoites", source: "SB 12.10886", period: "flavian_antonine" },
      { year: 138, rent_dr_ar: 52.0, nome: "Oxyrhynchites", source: "P. Oxy. 47.3354", period: "flavian_antonine" },
      { year: 150, rent_dr_ar: 60.0, nome: "Arsinoites", source: "BGU 3.915", period: "flavian_antonine" },
      { year: 155, rent_dr_ar: 56.0, nome: "Hermopolites", source: "P. Flor. 1.1", period: "flavian_antonine" },
      { year: 163, rent_dr_ar: 80.0, nome: "Arsinoites", source: "P. Lond. 2.179", notes: "high quality", period: "flavian_antonine" },
      { year: 175, rent_dr_ar: 100.0, nome: "Oxyrhynchites", source: "P. Oxy. 47.3355", period: "flavian_antonine" },
      { year: 185, rent_dr_ar: 72.0, nome: "Arsinoites", source: "BGU 1.96", period: "flavian_antonine" },
      { year: 197, rent_dr_ar: 120.0, nome: "Oxyrhynchites", source: "P. Oxy. 8.1125", period: "severan" },
      { year: 211, rent_dr_ar: 140.0, nome: "Hermopolites", source: "P. Flor. 3.366", period: "severan" },
      { year: 224, rent_dr_ar: 160.0, nome: "Oxyrhynchites", source: "P. Oxy. 47.3356", period: "severan" },
      { year: 248, rent_dr_ar: 200.0, nome: "Arsinoites", source: "P. Col. 7.188", notes: "Appianus estate", period: "crisis_3c" },
      { year: 255, rent_dr_ar: 240.0, nome: "Arsinoites", source: "P. Flor. 3.321", notes: "Appianus estate", period: "crisis_3c" },
      { year: 260, rent_dr_ar: 320.0, nome: "Arsinoites", source: "P. Prag. Varcl 2.1", period: "crisis_3c" }
    ],
    kind: [
      { year: 10, rent_art_ar: 2.5, nome: "Arsinoites", source: "BGU 4.1119", period: "julio_claudian" },
      { year: 26, rent_art_ar: 3.0, nome: "Arsinoites", source: "P. Mich. 5.312", period: "julio_claudian" },
      { year: 42, rent_art_ar: 4.0, nome: "Arsinoites", source: "P. Mich. 2.121", period: "julio_claudian" },
      { year: 46, rent_art_ar: 3.5, nome: "Arsinoites", source: "P. Mich. 2.123", period: "julio_claudian" },
      { year: 78, rent_art_ar: 5.0, nome: "Hermopolites", source: "SB 8.9699", notes: "Didymos estate", period: "flavian_antonine" },
      { year: 86, rent_art_ar: 4.0, nome: "Arsinoites", source: "P. Fay. 94", period: "flavian_antonine" },
      { year: 93, rent_art_ar: 5.5, nome: "Oxyrhynchites", source: "PSI 8.892", period: "flavian_antonine" },
      { year: 100, rent_art_ar: 5.0, nome: "Hermopolites", source: "P. Sarap. 3", period: "flavian_antonine" },
      { year: 110, rent_art_ar: 6.0, nome: "Arsinoites", source: "P. Mil. Vogl. 4.212", notes: "Patron estate", period: "flavian_antonine" },
      { year: 125, rent_art_ar: 5.0, nome: "Hermopolites", source: "P. Flor. 1.2", period: "flavian_antonine" },
      { year: 138, rent_art_ar: 6.5, nome: "Oxyrhynchites", source: "PSI 4.281", period: "flavian_antonine" },
      { year: 150, rent_art_ar: 6.0, nome: "Tebtynis", source: "P. Mil. Vogl. 7.302", period: "flavian_antonine" },
      { year: 165, rent_art_ar: 8.0, nome: "Arsinoites", source: "P. Mil. Vogl. 3.153", period: "flavian_antonine" },
      { year: 180, rent_art_ar: 7.0, nome: "Oxyrhynchites", source: "P. Oxy. 47.3354", period: "flavian_antonine" },
      { year: 200, rent_art_ar: 8.0, nome: "Hermopolites", source: "P. Flor. 3.366", period: "severan" },
      { year: 220, rent_art_ar: 9.0, nome: "Oxyrhynchites", source: "P. Oxy. 12.1578", period: "severan" },
      { year: 248, rent_art_ar: 10.0, nome: "Arsinoites", source: "P. Col. 7.188", notes: "Appianus estate", period: "crisis_3c" },
      { year: 255, rent_art_ar: 10.0, nome: "Arsinoites", source: "P. Flor. 3.321", period: "crisis_3c" },
      { year: 338, rent_art_ar: 3.0, nome: "Hermonthis", source: "P. Lips. 97", notes: "4C decline", period: "tetrarchy_constantine" },
      { year: 400, rent_art_ar: 5.0, nome: "various", source: "P. Oxy. 51.3628", period: "late_roman" },
      { year: 450, rent_art_ar: 6.0, nome: "Hermopolites", source: "P. Amh. 2.155", period: "late_roman" },
      { year: 500, rent_art_ar: 7.0, nome: "Oxyrhynchites", source: "P. Oxy. 16.2007", period: "byzantine_early" },
      { year: 550, rent_art_ar: 6.5, nome: "Aphrodites", source: "P.Cair. Masp. various", notes: "Dioscorus archive", period: "byzantine_early" },
      { year: 600, rent_art_ar: 5.5, nome: "Arsinoites", source: "SPP 8.1079", period: "byzantine_early" }
    ],
    solidi: [
      { year: 375, rent_sol_ar: 0.25, nome: "Oxyrhynchites", source: "P.Col. 8.238", period: "late_roman" },
      { year: 400, rent_sol_ar: 0.33, nome: "various", source: "P. Oxy. 51.3628", period: "late_roman" },
      { year: 450, rent_sol_ar: 0.5, nome: "Hermopolites", source: "P. Amh. 2.155", period: "late_roman" },
      { year: 500, rent_sol_ar: 0.4, nome: "Oxyrhynchites", source: "P. Oxy. 16.2007", period: "byzantine_early" },
      { year: 538, rent_sol_ar: 0.5, nome: "Aphrodites", source: "P.Cair. Masp. 1.67062", period: "byzantine_early" },
      { year: 566, rent_sol_ar: 0.45, nome: "Oxyrhynchites", source: "P. Oxy. 55.3805", notes: "Apion estate", period: "byzantine_early" },
      { year: 600, rent_sol_ar: 0.5, nome: "Arsinoites", source: "SPP various", period: "byzantine_early" }
    ]
  },

  purchasable_items: [
    { id: "wheat_artaba", name_en: "Artaba of Wheat", name_zh: "小麦(阿塔巴)", description_zh: "约40升，够一人吃一个月", category: "food", unit: "artaba", icon: "wheat" },
    { id: "wine_keramion", name_en: "Keramion of Wine", name_zh: "葡萄酒(陶罐)", description_zh: "约40升普通葡萄酒", category: "food", typical_price_drachmai: 8, icon: "wine" },
    { id: "olive_oil_kotyle", name_en: "Kotyle of Olive Oil", name_zh: "橄榄油(升)", description_zh: "约0.27升", category: "food", typical_price_obols: 2, icon: "oil" },
    { id: "tunic_basic", name_en: "Basic Tunic", name_zh: "普通束腰外衣", description_zh: "工人穿的基本服装", category: "clothing", typical_price_drachmai: 20, icon: "tunic" },
    { id: "donkey", name_en: "Donkey", name_zh: "驴", description_zh: "农用驮畜", category: "animal", typical_price_drachmai: 200, icon: "donkey" },
    { id: "slave_adult", name_en: "Adult Slave", name_zh: "成年奴隶", description_zh: "普通劳动力", category: "slave", typical_price_drachmai: 500, icon: "slave" },
    { id: "land_aroura", name_en: "Land Rent (1 year)", name_zh: "一年土地租金", description_zh: "一阿鲁拉(约0.27公顷)年租", category: "property", icon: "land" }
  ],

  occupations: [
    { id: "farmer_tenant", name_en: "Tenant Farmer", name_zh: "佃农", description_zh: "租种他人土地，缴纳实物或现金地租", social_class: "lower" },
    { id: "farm_laborer", name_en: "Farm Day Laborer", name_zh: "农业雇工", description_zh: "按日计酬的农业工人", social_class: "lower" },
    { id: "craftsman", name_en: "Craftsman/Artisan", name_zh: "工匠", description_zh: "木匠、铁匠、陶工、织工等", social_class: "middle_lower" },
    { id: "soldier_legionary", name_en: "Legionary Soldier", name_zh: "军团士兵", description_zh: "罗马军团正规士兵", social_class: "middle" },
    { id: "estate_manager", name_en: "Estate Manager", name_zh: "庄园管家", description_zh: "管理大庄园的专业人员", social_class: "middle" },
    { id: "scribe", name_en: "Scribe/Secretary", name_zh: "书记员", description_zh: "专业文书工作者", social_class: "middle" },
    { id: "merchant", name_en: "Small Merchant", name_zh: "小商贩", description_zh: "本地市场的商人", social_class: "middle" },
    { id: "landowner_small", name_en: "Small Landowner", name_zh: "自耕农/小地主", description_zh: "拥有小块土地的农民", social_class: "middle" },
    { id: "priest", name_en: "Temple/Church Priest", name_zh: "祭司/神父", description_zh: "宗教职业者", social_class: "middle_upper" },
    { id: "landowner_large", name_en: "Large Landowner", name_zh: "大地主", description_zh: "拥有大量土地的富人", social_class: "upper" }
  ]
};
